baseURL = "https://meetscience.it/"
languageCode = "it-IT"
title = "Meet Science"
theme = "meetscience"
#[menu]
#  [[menu.main]]
#    name = "Posts"
#    pre = "pen-tool"
#    url = "/posts/"
#    weight = 2